web_libros_django/migracion_db/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
urlpatterns = [
    path('agregar/', views.agregar_libro, name='agregar_libro'),  # Ruta para agregar un libro
    path('libros/', views.libro_list, name='libro_list'),  # Ruta para listar libros
    path('', views.libro_list, name='libro_list'),
    path('editar/<int:libro_id>/', views.libro_editar, name='libro_editar'),
    path('protegida/', views.pagina_protegida, name='pagina_protegida'),

    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('obtener_informacion_libro/', views.obtener_informacion_libro, name='obtener_informacion_libro'),

    path('home/', views.home, name='home'),  # Asegúrate de tener una página de inicio


]

web_libros_django/web_libros_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Ruta para el panel de administración de Django
    path('admin/', admin.site.urls),

    # Incluir las rutas de la aplicación migracion_db
    path('migracion_db/', include('migracion_db.urls')),  # Esto incluye las rutas de migracion_db
    
    # Otras posibles rutas que puedas tener en el futuro...
]

web_libros_django/migracion_db/models.py
from django.db import models
from django.contrib.auth.models import User

class Libro(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='libros', null=True, blank=True)
    titulo = models.CharField(max_length=255, null=True, blank=True)
    autor = models.CharField(max_length=255, null=True, blank=True)
    tipo = models.CharField(max_length=255, null=True, blank=True)
    fecha_termino = models.DateField(null=True, blank=True)
    puntuacion = models.FloatField(null=True, blank=True)
    opinion = models.TextField(null=True, blank=True)
    tag = models.CharField(max_length=1000, null=True, blank=True)
    fecha_agregada = models.DateField(null=True, blank=True)
    foto_url = models.URLField()

    def __str__(self):
        return f"{self.titulo} ({self.user.username})"

from django.db import models
from django.contrib.auth.models import User

class UserData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_data')
    data_field = models.CharField(max_length=255)  # Personaliza este campo según tu necesidad
    created_at = models.DateTimeField(auto_now_add=True)  # Marca temporal automática

    def __str__(self):
        return f"{self.user.username} - {self.data_field}"

web_libros_django/migracion_db/forms.py
from django import forms
from .models import Libro
from datetime import date

class LibroForm(forms.ModelForm):
    # Bloquear los campos de título, autor y foto_url
    titulo = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    autor = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    foto_url = forms.URLField(required=False, widget=forms.URLInput(attrs={'readonly': 'readonly'}))

    # Nuevo campo para la URL que el usuario introducirá
    url_libro = forms.URLField(required=False, widget=forms.URLInput(attrs={'placeholder': 'Introduce la URL del libro'}))

    class Meta:
        model = Libro
        fields = ['titulo', 'autor', 'opinion', 'tag', 'puntuacion', 'foto_url', 'fecha_termino', 'fecha_agregada', 'url_libro']
    
    # Campo de fecha de término con selector de fecha
    fecha_termino = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}), 
        required=False
    )
    
    # Campo de fecha agregada con la fecha de hoy por defecto
    fecha_agregada = forms.DateField(
        widget=forms.HiddenInput(),  
        initial=date.today
    )

    # Campo de opinión
    opinion = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Escribe tu opinión sobre el libro'}))

from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return cleaned_data

web_libros_django/migracion_db/views.py
from .models import Libro
from .forms import LibroForm
from datetime import date
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.db.models import Q  # Importar Q para condiciones OR
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from django.shortcuts import render, redirect
from .forms import LibroForm

from datetime import date
from .utils import obtener_info  # Importamos la función que hace el scraping
@login_required
def agregar_libro(request):
    if request.method == 'POST':
        form = LibroForm(request.POST)
        if form.is_valid():
            libro = form.save(commit=False)
            
            # Si la URL es válida, completamos los campos bloqueados
            url_libro = form.cleaned_data.get('url_libro')
            if url_libro:
                if 'casadellibro.com' in url_libro or 'goodreads.com' in url_libro:
                    title, autor, imagen = obtener_info(url_libro)
                    libro.titulo = title if title else libro.titulo
                    libro.autor = autor if autor else libro.autor
                    libro.foto_url = imagen if imagen else libro.foto_url

            # Asignar el usuario y fecha
            libro.user = request.user
            libro.fecha_termino = date.today()  # Puedes cambiar esto según tu lógica
            libro.save()
            return redirect('libro_list')
    else:
        form = LibroForm()

    return render(request, 'agregar_libro.html', {'form': form})

@login_required
def libro_editar(request, libro_id):
    libro = get_object_or_404(Libro, id=libro_id, user=request.user)  # Verificar que el usuario sea el propietario

    if request.method == 'POST':
        form = LibroForm(request.POST, instance=libro)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cambios guardados correctamente.')
            return redirect('libro_list')
    else:
        form = LibroForm(instance=libro)

    return render(request, 'libro_editar.html', {'form': form, 'libro': libro})
# def libro_list(request):
#     # Obtener todos los libros
#     libros_filtrados = Libro.objects.all()

#     # Obtener los filtros aplicados
#     año = request.GET.get('año', '')  
#     mes = request.GET.get('mes', '')  
#     busqueda = request.GET.get('busqueda', '')

#     # Filtrar por año si se ha seleccionado un valor
#     if año and año != "":
#         try:
#             año = int(año)  # Asegurarse de que el año sea un entero
#             libros_filtrados = libros_filtrados.filter(fecha_termino__year=año)
#         except ValueError:
#             pass  # Si no se puede convertir a entero, no hacer el filtro
    
#     # Filtrar por mes si se ha seleccionado un valor
#     if mes and mes != "":
#         try:
#             mes = int(mes)  # Asegurarse de que el mes sea un entero
#             libros_filtrados = libros_filtrados.filter(fecha_termino__month=mes)
#         except ValueError:
#             pass  # Si no se puede convertir a entero, no hacer el filtro
    
#     # Filtrar por búsqueda si se ha ingresado algo
#     if busqueda:
#         libros_filtrados = libros_filtrados.filter(
#             Q(titulo__icontains=busqueda) | 
#             Q(autor__icontains=busqueda) | 
#             Q(tag__icontains=busqueda)
#         )

#     # Filtros adicionales por puntuación
#     puntuacion_min = request.GET.get('puntuacion_min', None)
#     puntuacion_max = request.GET.get('puntuacion_max', None)
#     if puntuacion_min:
#         libros_filtrados = libros_filtrados.filter(puntuacion__gte=puntuacion_min)
#     if puntuacion_max:
#         libros_filtrados = libros_filtrados.filter(puntuacion__lte=puntuacion_max)

#     # Ordenar por la opción seleccionada
#     ordenar_por = request.GET.get('ordenar_por', None)
#     if ordenar_por == 'puntuacion':
#         libros_filtrados = libros_filtrados.order_by('-puntuacion')
#     elif ordenar_por == 'fecha_termino':
#         libros_filtrados = libros_filtrados.order_by('-fecha_termino')

#     # Obtener los años y meses únicos para los filtros
#     años_disponibles = sorted(Libro.objects.values_list('fecha_termino__year', flat=True).distinct())
#     meses_disponibles = sorted(Libro.objects.values_list('fecha_termino__month', flat=True).distinct())

#     # Contar el número de libros que se muestran
#     total_libros = libros_filtrados.count()

#     # Si se va a eliminar uno o más libros
#     if request.method == 'POST' and 'eliminar_libros' in request.POST:
#         ids_a_eliminar = request.POST.getlist('eliminar_ids')
#         libros_filtrados.filter(id__in=ids_a_eliminar).delete()
#         return redirect('libro_list')  # Redirige a la misma página después de eliminar

#     # Renderizar la plantilla con los filtros, libros y el contador
#     return render(request, 'libro_list.html', {
#         'libros': libros_filtrados,
#         'años': años_disponibles,
#         'meses': meses_disponibles,
#         'año': año,
#         'mes': mes,
#         'busqueda': busqueda,
#         'puntuacion_min': puntuacion_min,
#         'puntuacion_max': puntuacion_max,
#         'ordenar_por': ordenar_por,
#         'total_libros': total_libros,  # Agregar el total de libros filtrados
#     })


@login_required
def libro_list(request):
    libros_filtrados = Libro.objects.filter(user=request.user)  # Filtrar libros del usuario actual

    # Mantén el resto del código de filtros y búsquedas
    año = request.GET.get('año', '')  
    mes = request.GET.get('mes', '')  
    busqueda = request.GET.get('busqueda', '')
    if request.method == 'POST':
        import json
        data = json.loads(request.body)
        eliminar_id = data.get('eliminar_id')
        if eliminar_id:
            Libro.objects.filter(id=eliminar_id, user=request.user).delete()
            return JsonResponse({'success': True})
        return JsonResponse({'success': False, 'message': 'ID no válido'}, status=400)
    if año:
        try:
            año = int(año)
            libros_filtrados = libros_filtrados.filter(fecha_termino__year=año)
        except ValueError:
            pass

    if mes:
        try:
            mes = int(mes)
            libros_filtrados = libros_filtrados.filter(fecha_termino__month=mes)
        except ValueError:
            pass

    if busqueda:
        libros_filtrados = libros_filtrados.filter(
            Q(titulo__icontains=busqueda) | 
            Q(autor__icontains=busqueda) | 
            Q(tag__icontains=busqueda)
        )

    total_libros = libros_filtrados.count()

    return render(request, 'libro_list.html', {
        'libros': libros_filtrados,
        'total_libros': total_libros,
    })



from django.contrib import messages
# def libro_editar(request, libro_id):
#     # Obtener el libro a editar
#     libro = get_object_or_404(Libro, id=libro_id)

#     if request.method == 'POST':
#         form = LibroForm(request.POST, instance=libro)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Se guardaron correctamente los cambios.')
#             return redirect('libro_list')  # Redirige a la lista de libros
#     else:
#         form = LibroForm(instance=libro)

#     return render(request, 'libro_editar.html', {
#         'form': form,
#         'libro': libro,
#     })



from django.contrib.auth.views import LoginView

class MiLoginView(LoginView):
    template_name = 'login.html'

@login_required
def pagina_protegida(request):
    return render(request, 'pagina_protegida.html', {'mensaje': 'Estás autenticado'})
from .forms import UserRegistrationForm


from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            # Crea el nuevo usuario, pero no lo guarda aún
            user = form.save(commit=False)
            
            # Establece la contraseña de forma segura (encriptada)
            user.set_password(form.cleaned_data['password'])
            
            # Guarda el usuario en la base de datos
            user.save()
            
            # Inicia sesión con el nuevo usuario
            login(request, user)
            
            # Redirige al usuario a la página de inicio (o la que prefieras)
            return redirect('home')
    else:
        form = UserRegistrationForm()

    return render(request, 'register.html', {'form': form})

from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)  # Inicia sesión con el usuario
            return redirect('home')  # Redirige a la página principal después del login
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def home(request):
    return render(request, 'home.html')  # Crea una plantilla para la página principal

from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_view(request):
    logout(request)  # Cierra la sesión del usuario
    return redirect('login')  # Redirige al usuario a la página de login (o donde prefieras)



from django.http import JsonResponse
from .utils import obtener_info


def obtener_informacion_libro(request):
    if request.method == 'POST':
        url = request.POST.get('url')
        
        if url:
            title, author, image = obtener_info(url)

            if title and author and image:
                return JsonResponse({
                    'success': True,
                    'title': title,

web_libros_django/migracion_db/templates/agregar_libro.html
{% extends 'base.html' %}

{% block title %}Agregar un Libro{% endblock %}

{% block content %}
    <div class="container">
        <!-- <h1>Agregar un Libro</h1> -->
        <form method="POST" class="form-container">
            {% csrf_token %}
            <!-- Nuevo campo para la URL del libro -->
            <div class="form-group">
                <label for="libro_url">URL del Libro:</label>
                <input type="text" id="libro_url" class="form-control" placeholder="Ingrese la URL del libro">
                <button type="button" id="buscar_libro" class="btn btn-primary">Buscar</button>
            </div>
            <div class="form-group">
                <label for="titulo">Título:</label>
                {{ form.titulo }}
            </div>
            <div class="form-group">
                <label for="autor">Autor:</label>
                {{ form.autor }}
            </div>
            <div class="form-group">
                <label for="opinion">Opinión:</label>
                {{ form.opinion }}
            </div>
            <div class="form-group">
                <label for="tag">Etiqueta(s):</label>
                {{ form.tag }}
            </div>
            <div class="form-group">
                <label for="puntuacion">Puntuación (1-5):</label>
                {{ form.puntuacion }}
            </div>
            <!-- <div class="form-group">
                <label for="foto_url">URL de la Foto (opcional):</label> -->
                
                <!-- <p class="optional-field">Deja este campo vacío si no tienes una URL para la foto.</p>
            </div> -->
            <div class="form-group">
                <label for="fecha_termino">Fecha de Terminación:</label>
                {{ form.fecha_termino }}
            </div>
            <!-- Campo oculto para la fecha agregada -->
            {{ form.fecha_agregada }}
            <!-- Campo oculto para la fecha agregada -->
            {{ form.foto_url }}



            <button type="submit">Guardar</button>
        </form>

        <!-- Cuadro para mostrar la imagen -->
        <div id="imagen_libro" class="imagen-libro">
            <img id="imagen_libro_url" src="" alt="Imagen del libro" style="display: none;">
        </div>

        <a href="{% url 'libro_list' %}" class="link-btn">Volver a la lista de libros</a>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        document.getElementById('buscar_libro').addEventListener('click', function() {
            var libroUrl = document.getElementById('libro_url').value;
            
            if (libroUrl && libroUrl.includes('casadellibro.com') || libroUrl.includes('goodreads.com')) {
                $.ajax({
                    url: '/migracion_db/obtener_informacion_libro/',  // URL con el prefijo adecuado
                    method: 'POST',
                    data: {
                        'url': libroUrl,
                        'csrfmiddlewaretoken': document.querySelector('[name="csrfmiddlewaretoken"]').value
                    },
                    success: function(response) {
                        if (response.success) {
                            document.getElementById('id_titulo').value = response.title;
                            document.getElementById('id_autor').value = response.author;
                            document.getElementById('id_foto_url').value = response.image;

                            // Mostrar la imagen
                            var imagen = document.getElementById('imagen_libro_url');
                            imagen.src = response.image;
                            imagen.style.display = 'block'; // Mostrar la imagen
                        } else {
                            alert("No se pudo obtener la información del libro.");
                        }
                    },
                    error: function() {
                        alert("Hubo un error al intentar obtener la información.");
                    }
                });
            } else {
                alert("Por favor, ingresa una URL válida de Casa del Libro o Goodreads.");
            }
        });
    </script>

    <style>
        .container {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: flex-start;
        }

        .form-container {
            width: 60%; /* Ajusta el tamaño del formulario */
        }

        .imagen-libro {
            width: 35%; /* Ajusta el tamaño de la imagen */
            height: 500px; /* Ajusta la altura de la imagen */
            border: 1px solid #ccc;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 10px;
        }

        .imagen-libro img {
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
        }

        .link-btn {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 10px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-size: 16px;
        }

        .link-btn:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

web_libros_django/migracion_db/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=1.0">

</head>
<body>
    <header class="header">
        <h1><a href="{% url 'libro_list' %}">Mi Biblioteca</a></h1>
        <div>
            {% if user.is_authenticated %}
                <span>Bienvenido, {{ user.username }}</span>
                <a href="{% url 'logout' %}" style="margin-left: 10px; color: red;">Cerrar sesión</a>
            {% else %}
                <a href="{% url 'login' %}" style="color: green;">Iniciar sesión</a>
            {% endif %}
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

web_libros_django/migracion_db/templates/home.html
{% if user.is_authenticated %}
  <h2>Bienvenido, {{ user.username }}!</h2>
  <p>Estás autenticado correctamente.</p>
{% else %}
  <p>No has iniciado sesión.</p>
{% endif %}

web_libros_django/migracion_db/templates/libro_editar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Libro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        form {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        label {
            font-size: 16px;
            margin-bottom: 5px;
        }

        input[type="text"], input[type="number"], input[type="date"], input[type="url"], textarea, select {
            padding: 10px;
            font-size: 16px;
            border-radius: 4px;
            border: 1px solid #ddd;
            width: 100%;
        }

        textarea {
            resize: vertical;
            height: 100px;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        .cancelar-btn {
            background-color: #f44336;
        }

        .cancelar-btn:hover {
            background-color: #d32f2f;
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

            /* Incluye el estilo de los enlaces aquí */
            .link-btn {
            display: inline-block;
            padding: 10px 15px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            text-align: center;
            font-weight: bold;
            margin-top: 20px;
            transition: background-color 0.3s, transform 0.2s;
        }

        .link-btn:hover {
            background-color: #0056b3;
            transform: scale(1.05);
        }

        .link-btn:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 123, 255, 0.8);
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Editar Libro: {{ libro.titulo }}</h1>

        <form method="POST">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_titulo">Título</label>
                {{ form.titulo }}
            </div>

            <div class="form-group">
                <label for="id_autor">Autor</label>
                {{ form.autor }}
            </div>

            <div class="form-group">
                <label for="id_puntuacion">Puntuación</label>
                {{ form.puntuacion }}
            </div>

            <div class="form-group">
                <label for="id_fecha_termino">Fecha de Término</label>
                {{ form.fecha_termino }}
            </div>

            <div class="form-group">
                <label for="id_opinion">Opinión</label>
                {{ form.opinion }}
            </div>

            <div class="form-group">
                <label for="id_foto_url">URL de la Foto</label>
                {{ form.foto_url }}
            </div>

            <div class="form-group">
                <label for="id_tag">Tags</label>
                {{ form.tag }}
            </div>

            <div class="form-group">
                <button type="submit">Guardar Cambios</button>
                <a href="{% url 'libro_list' %}">
                    <button type="button" class="cancelar-btn">Cancelar</button>
                </a>
            </div>
        </form>
        <a href="{% url 'libro_list' %}" class="link-btn">Volver a la lista de libros</a>
    </div>

</body>
</html>

web_libros_django/migracion_db/templates/libro_list.html
{% extends 'base.html' %}

{% block title %}Libros{% endblock %}

{% block content %}

    <!-- Buscador en la parte superior, al lado de ordenar por -->


    <a href="{% url 'agregar_libro' %}" class="link-btn">Agregar un nuevo libro</a>
    <div id="search-form">
        <form method="GET">
            <!-- Ordenar por -->
            <select name="ordenar_por" onchange="this.form.submit()">
                <option value="">Ordenar por</option>
                <option value="puntuacion" {% if ordenar_por == 'puntuacion' %}selected{% endif %}>Puntuación</option>
                <option value="fecha_termino" {% if ordenar_por == 'fecha_termino' %}selected{% endif %}>Fecha de Término</option>
            </select>
            
            <!-- Campo de búsqueda (vacío por defecto) -->
            <input type="text" name="busqueda" value="{{ busqueda | default:'' }}" placeholder="Buscar por título, autor, tag, etc." />

            <!-- Botón de búsqueda -->
            <button type="submit" name="accion" value="buscar">Buscar</button>
        </form>
    </div>

    <!-- Contenedor para filtros y libros -->
    <div class="container">
        <!-- Filtros a la izquierda -->
        <div class="filters">
            <h2>Filtros</h2>
            <form method="GET">
                <!-- Filtro por puntuación -->
                <label for="puntuacion_min">Puntuación Mínima</label>
                <input type="number" name="puntuacion_min" min="0" max="5" step="0.1" value="{{ puntuacion_min }}" />

                <label for="puntuacion_max">Puntuación Máxima</label>
                <input type="number" name="puntuacion_max" min="0" max="5" step="0.1" value="{{ puntuacion_max }}" />

                <!-- Filtro por año -->
                <select name="año">
                    <option value="">Seleccionar Año</option>
                    {% for año in años %}
                        <option value="{{ año }}" {% if año == año %}selected{% endif %}>{{ año }}</option>
                    {% endfor %}
                </select>
                
                <!-- Filtro de Mes -->
                <select name="mes">
                    <option value="">Seleccionar Mes</option>
                    {% for mes in meses %}
                        <option value="{{ mes }}" {% if mes == mes %}selected{% endif %}>{{ mes }}</option>
                    {% endfor %}
                </select>

                <!-- Ordenar por -->
                <label for="ordenar_por">Ordenar por</label>
                <select name="ordenar_por" onchange="this.form.submit()">
                    <option value="">Seleccionar opción</option>
                    <option value="puntuacion" {% if ordenar_por == 'puntuacion' %}selected{% endif %}>Puntuación</option>
                    <option value="fecha_termino" {% if ordenar_por == 'fecha_termino' %}selected{% endif %}>Fecha de Término</option>
                </select>

                <button type="submit" name="accion" value="aplicar_filtros">Aplicar Filtros</button>
            </form>
            <p class="contador-libros">Total de {{ total_libros }} libros.</p>
        </div>

        <!-- Listado de libros -->
 
        <div class="book-list">
            {% for libro in libros %}
                <div class="book-card">
                    <a href="javascript:void(0);" onclick="alert('{{ libro.opinion }}')">
                        <img src="{{ libro.foto_url }}" alt="Foto de {{ libro.titulo }}" />
                    </a>
                    <h3>{{ libro.titulo }}</h3>
                    <p class="rating">Puntuación: {{ libro.puntuacion }}</p>
                    <p>{{ libro.fecha_termino|date:"Y-m-d" }}</p>
        
                    <!-- Botones de acción -->
                    <div class="action-buttons">
                        <a href="{% url 'libro_editar' libro.id %}" class="btn btn-edit">Editar</a>

                        <button class="btn btn-delete" onclick="eliminarLibro({{ libro.id }})">Eliminar</button>
                    </div>
                </div>
            {% endfor %}
        </div>

        <script>
            function eliminarLibro(libroId) {
                if (!confirm("¿Estás seguro de que quieres eliminar este libro?")) {
                    return;
                }
            
                fetch("{% url 'libro_list' %}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}",
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({ eliminar_id: libroId })
                })
                .then(response => {
                    if (response.ok) {
                        document.getElementById(`book-${libroId}`).remove();
                        alert("Libro eliminado correctamente.");
                    } else {
                        alert("Hubo un problema al eliminar el libro.");
                    }
                })
                .catch(error => console.error("Error:", error));
            }
            </script>
    <script>
        // Función para manejar la confirmación de eliminación
        // function confirmDelete() {
        //     const selectedBooks = getSelectedBooks();
        //     if (selectedBooks.length === 0) {
        //         alert('No has seleccionado ningún libro para eliminar.');
        //         return;
        //     }

        //     document.getElementById('confirm-message').style.display = 'block';
        // }

        // Función para obtener los libros seleccionados
        function getSelectedBooks() {
            const checkboxes = document.querySelectorAll('.book-card input[type="checkbox"]:checked');
            return Array.from(checkboxes).map(checkbox => checkbox.value);
        }

        // Función para ejecutar la eliminación
        function confirmDeleteAction() {
            const selectedBooks = getSelectedBooks();
            document.getElementById('delete-ids').value = selectedBooks.join(',');
            document.getElementById('delete-form').submit();
        }

        // Función para cancelar la eliminación
        function cancelDelete() {
            document.getElementById('confirm-message').style.display = 'none';
        }
    </script>

{% endblock %}